name: coinfo_app
description: A new Flutter project.

publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  chart_sparkline: ^1.0.11
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_svg: ^2.0.7
  form_validator: ^2.1.1
  google_fonts: ^6.0.0
  http: ^1.1.0
  intl: ^0.18.1
  supabase_flutter: ^1.0.1
  flutter_switch: ^0.3.2
  fl_chart: ^0.63.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/
